stages:
    - test

variables:
  PRIMARY_VERSION: 38
  IMAGE_ROOT: "python"
  PRIMARY_IMAGE: $IMAGE_ROOT$PRIMARY_VERSION


unit-tests:
  stage: test
  parallel:
    matrix:
      - PY_VERSION: [ "3.8", "3.9" ]
  image: $IMAGE_ROOT:$PY_VERSION
  before_script:
    - python -m pip install Cython numpy
    - python -m pip install pytest-cov
    - python -m pip install bilby
    - python -m pip install lalsuite
  script:
    - python setup.py clean --all build_ext --force --inplace --debug
    - pytest . --cov=bilby_cython
  after_script:
    - coverage html
    - mv htmlcov htmlcov_$PY_VERSION
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - htmlcov_$PY_VERSION/
      - coverage.xml
    expire_in: 30 days
